@library_reservationAPI_HostAddress = http://localhost:5144

GET {{library_reservationAPI_HostAddress}}/api/books
Accept: application/json
Guid: {{$guid}}

###

GET {{library_reservationAPI_HostAddress}}/api/books/1
Accept: application/json
Guid: {{$guid}}

###

GET {{library_reservationAPI_HostAddress}}/api/books?page=1&recordsPerPage=5&type=books&year=1922
Accept: application/json
Guid: {{$guid}}

